name: Environment Approval

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo Building code

  deploy_Intergration:
    needs: [build]
    runs-on: ubuntu-latest
    environment: intergration
    steps:
      - name: test
        run: echo deploy to environment intergration

  deploy_QA:
    needs: [deploy_Intergration]
    runs-on: ubuntu-latest
    environment: qa
    steps:
      - name: test
        run: echo deploy to environment QA

  deploy_UAT:
    needs: [deploy_QA]
    runs-on: ubuntu-latest
    environment: uat
    steps:
      - name: test
        run: echo deploy to environment UAT

  deploy_Production:
    needs: [deploy_UAT]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: test
        run: echo deploy to environment Production